[project]
name = "latent_space_explorer"
description = "UI application for exploring a latent space learned by DeepSDF, by interactively generating 3D shapes from weighted latent codes"
version = "0.0.1"
authors = [{name = "Roel Webb"}]

requires-python = ">=3.11, <3.15"


dependencies = [
  "torch",
  "numpy",
  "pyqt5",
  "matplotlib",
  "moderngl",
  "trimesh",
  "scipy",
  "torch-pca",
  "cuml-cu12",
  "mdscuda",
  "pyrr",
  "scikit-image",
  "gdown",
  "scikit-learn",

  "plyfile" # DeepSDF mesh generation dependency
]


license = "MIT"
license-files = ["LICENSE"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
repository = "https://github.com/RoelWebb/latent_space_explorer"

[[tool.uv.index]]
name = "pytorch_index"
url = "https://download.pytorch.org/whl"
explicit = true

[[tool.uv.index]]
name = "cuml_index"
url = "https://pypi.nvidia.com"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch_index" }
cuml-cu12 = { index = "cuml_index" }

# CI/CD dependencies
[project.optional-dependencies]
test = ["pytest"]
dev = ["flake8"]